const carrierBOLHeader = "Carrier BOL"
const packageIdHeader = "Package Id"
const trackingIdHeader = "Tracking ID"
const processedDateTimeHeader = "Processed Date/Time"
const actualWeightHeader = "Actual Weight"
const billedWeightHeader = "Billed Weight"
const billedServiceHeader = "Billed Service"
const zipHeader = "Zip"
const zoneHeader = "Zone"
const packageChargeHeader = "Package Charge"
const deliveryConfirmationChargeHeader = "Delivery Confirmation Charge"
const fuelChargeHeader = "Fuel Charge"
const miscSurchargeHeader = "MISC Surcharge"
const carrierDimSurchargeHeader = "Carrier DIM Surcharge"
const totalChargeHeader = "Total Charge"
const heightHeader = "Height"
const lengthHeader = "Length"
const widthHeader = "Width"
const costCenterNameHeader = "Cost Center Name"
const dimRulesAppliedHeader = "DIM Rules Applied"
const relabelFeeHeader = "Relabel Fee"
const dasHeader = "Delivery Area Surcharge (DAS)"
const ocrHeader = "OCR Fee"
const peakHeader = "Peak Season Surcharge"
const nonstandardLengthFee22Header = "Nonstandard Length Fee 22 in"
const nonstandardLengthFee30Header = "Nonstandard Length Fee 30 in"
const nonstandardLengthFee2cuHeader = "Nonstandard Length Fee 2 cu"
const dimensionNoncomplianceHeader = "Dimension Noncompliance"
const irregularShapeChargeHeader = "Irregular Shape Charge"


// (packageCharge + deliveryConfirmationCharge + fuelSurcharge + miscSurcharge + carrierDIMSurcharge) === totalCharge
// (relabelFee + dasSurcharge + ocrFee + peakSurcharge + nsl22fee + nsl30fee + nsl2cufee + dimNoncompliance + irregularShapeCharge) === totalCharge
